DROP DATABASE IF EXISTS follyemployees_db;
CREATE DATABASE follyemployees_db;

\c follyemployees_db;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255)
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
);
